PACKAGE_NAME = gworkspace
include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = kdialog

kdialog_OBJC_FILES = kdialog.m

-include GNUmakefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/tool.make

-include GNUmakefile.postamble
