only_if: $CIRRUS_BRANCH == 'main' && $CIRRUS_PR == ''

trigger_ports_build_task:
  name: "Trigger ports build"
  container:
    image: curlimages/curl:latest
  
  trigger_script:
    - |
      curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        -d '{
          "event_type": "workspace_merge",
          "client_payload": {
            "workspace_commit": "'$CIRRUS_CHANGE_IN_REPO'",
            "workspace_branch": "'$CIRRUS_BRANCH'",
            "triggered_by": "gershwin-workspace"
          }
        }' \
        "https://api.github.com/repos/gershwin-desktop/gershwin-unstable-ports/dispatches"
  
  env:
    GITHUB_TOKEN: ENCRYPTED[2044e69b6c0b98831e048d8a0802403d9f0b57c31f4bc4d175b379367f0225b6acc08d9a8c6adf47d109739e4e07b3e8]
