/* confdefs.h */
#define PACKAGE_NAME "gworkspace"
#define PACKAGE_TARNAME "gworkspace"
#define PACKAGE_VERSION "1.1.0"
#define PACKAGE_STRING "gworkspace 1.1.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_GETPWNAM 1
#define HAVE_GETPWUID 1
#define HAVE_GETEUID 1
#define HAVE_GETLOGIN 1
#define HAVE_SQFS_PREDEF_H 1
#define HAVE_DBUS 1
#define HAVE_SQUASHFS 1
#define GW_DEBUG_LOG 0
#define HAVE_SYS_INOTIFY_H 1
#define HAVE_DISPATCH_DISPATCH_H 1
#define HAVE_DISPATCH_PRIVATE_H 1
