PACKAGE_NAME = gworkspace
include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = BadgeTest

BadgeTest_OBJC_FILES = main.m

BadgeTest_RESOURCE_FILES = Resources/Info-gnustep.plist

-include GNUmakefile.preamble
-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/application.make

-include GNUmakefile.postamble
