/* t_FSNAliasInterop.m — macOS <-> Gershwin Alias record interoperability.
 *
 * Verifies that FSNAlias (FSNode/FSNAlias.m) correctly parses REAL alias
 * records produced by a real Mac.  The fixtures (*.alis + MANIFEST.plist) are
 * generated by Tools/mac-alias-interop/generate-alias-fixtures.sh, which needs
 * ssh access to a Mac; this test is hermetic and never touches the network - it
 * only consumes the staged artifacts.  Without staged fixtures it skips cleanly
 * so the suite stays green on machines without a Mac.
 *
 * Covered (ground truth captured from macOS itself):
 *   - the 'alis' magic is recognised
 *   - the record version (2/3) is read
 *   - target name, is-directory kind, and volume name parse correctly
 *   - the POSIX path TLV (when present) matches
 *   - resolvePath finds the target at the recorded absolute path
 *
 * SPDX-License-Identifier: GPL-2.0-or-later OR BSD-2-Clause
 */

#import <Foundation/Foundation.h>
#import "Testing.h"

/* The unit under test, compiled in-process (headless). */
#include "../../FSNode/FSNAlias.m"

/* ------------------------------------------------------------------ */
/* Locate the staged fixture directory without any build-system help. */
static NSString *
interopFixturesDir(void)
{
  NSMutableArray *candidates = [NSMutableArray array];

  const char *env = getenv("GW_INTEROP_FIXTURES");
  if (env && env[0])
    [candidates addObject: [NSString stringWithUTF8String: env]];

  NSString *exe = [[[NSProcessInfo processInfo] arguments] firstObject];
  if (exe)
    {
      NSString *dir = [exe stringByDeletingLastPathComponent];
      [candidates addObject:
        [[dir stringByDeletingLastPathComponent]
          stringByAppendingPathComponent: @"fixtures"]];
      /* When run as Tests/FSNode/obj/t_X the fixtures live in
       * Tests/FSNode/interop/fixtures. */
      [candidates addObject:
        [[[dir stringByDeletingLastPathComponent]
           stringByAppendingPathComponent: @"interop"]
          stringByAppendingPathComponent: @"fixtures"]];
    }

  char *cwdBuf = getcwd(NULL, 0);
  if (cwdBuf)
    {
      NSString *base = [NSString stringWithUTF8String: cwdBuf];
      free(cwdBuf);
      [candidates addObject: [base stringByAppendingPathComponent: @"fixtures"]];
      [candidates addObject: [base stringByAppendingPathComponent:
        @"Tests/FSNode/interop/fixtures"]];
    }

  for (NSString *dir in candidates)
    {
      if ([[NSFileManager defaultManager] fileExistsAtPath:
            [dir stringByAppendingPathComponent: @"MANIFEST.plist"]])
        return dir;
    }
  return nil;
}

#define U8(o) ((o) ? [(o) UTF8String] : "(nil)")

static void
testFixture(NSString *fixtureName, NSDictionary *truth,
            NSString *fixDir, NSFileManager *fm)
{
  NSString *path = [fixDir stringByAppendingPathComponent: fixtureName];
  NSData *raw = [NSData dataWithContentsOfFile: path];

  START_SET("interop alias fixture")
    {
      PASS(raw != nil, "fixture bytes loaded");
      PASS([FSNAlias isAliasData: raw], "alias magic recognised");

      FSNAlias *a = [[FSNAlias alloc] initWithData: raw];
      PASS(a != nil, "record parses");

      PASS([a version] == 2 || [a version] == 3, "version is 2 or 3");

      NSString *expName = [truth objectForKey: @"targetName"];
      PASS_EQUAL([a targetName], expName, "target name");

      NSNumber *expDir = [truth objectForKey: @"isDirectory"];
      PASS([a isDirectory] == [expDir boolValue], "is-directory kind");

      NSString *expVol = [truth objectForKey: @"volumeName"];
      if (expVol != nil && [expVol length])
        PASS_EQUAL([a volumeName], expVol, "volume name");

      NSString *expPosix = [truth objectForKey: @"posixPath"];
      if (expPosix != nil)
        {
          BOOL posixOk = ([a posixPath] != nil)
            && [[a posixPath] isEqualToString: expPosix];
          PASS(posixOk, "posix path matches");
        }

      /* Resolution: recreate the target at the recorded absolute path on this
       * box, then confirm the alias resolves to it.  Mac-originated paths such
       * as /Users/... cannot be recreated here, so we skip gracefully. */
      if (expPosix != nil && [expPosix length])
        {
          BOOL made = NO;
          if ([expDir boolValue])
            made = [fm createDirectoryAtURL:
                     [NSURL fileURLWithPath: expPosix isDirectory: YES]
                                       withIntermediateDirectories: YES
                                                attributes: nil error: NULL];
          else
            made = [[expPosix dataUsingEncoding: NSUTF8StringEncoding]
                     writeToFile: expPosix atomically: NO];
          if (made)
            {
              NSString *resolved = [a resolvePath];
              PASS_EQUAL(resolved, expPosix, "resolvePath finds target");
              [fm removeItemAtPath: expPosix error: NULL];
            }
          else
            {
              PASS(1, "target recreation skipped (foreign path)");
            }
        }
    }
  END_SET("interop alias fixture")
}

int
main(void)
{
  NSAutoreleasePool *arp = [NSAutoreleasePool new];
  NSFileManager *fm = [NSFileManager defaultManager];

  NSString *fixDir = interopFixturesDir();
  if (fixDir == nil)
    {
      fprintf(stderr,
        "t_FSNAliasInterop: no fixtures found (run "
        "Tools/mac-alias-interop/generate-alias-fixtures.sh) - SKIP\n");
      [arp release];
      return 0;
    }
  printf("t_FSNAliasInterop: fixtures from %s\n", U8(fixDir));

  NSDictionary *manifest = [NSDictionary dictionaryWithContentsOfFile:
    [fixDir stringByAppendingPathComponent: @"MANIFEST.plist"]];
  if (manifest == nil)
    {
      fprintf(stderr, "t_FSNAliasInterop: MANIFEST.plist unreadable - SKIP\n");
      [arp release];
      return 0;
    }

  [manifest enumerateKeysAndObjectsUsingBlock:
    ^(id fixtureName, id truth, BOOL *stop)
    {
      testFixture((NSString *)fixtureName, (NSDictionary *)truth,
                  fixDir, fm);
    }];

  [arp release];
  return 0;
}
