
PACKAGE_NAME = gworkspace
include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

BUNDLE_NAME = MDModuleAnnotations
BUNDLE_EXTENSION = .mdm

OBJCFLAGS += -Wall

MDModuleAnnotations_OBJC_FILES = MDModuleAnnotations.m 

MDModuleAnnotations_PRINCIPAL_CLASS = MDModuleAnnotations

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble


