
PACKAGE_NAME = gworkspace
include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

BUNDLE_NAME = AVThumbnailer
BUNDLE_EXTENSION = .thumb

OBJCFLAGS += -Wall

AVThumbnailer_OBJC_FILES = AVThumbnailer.m

AVThumbnailer_PRINCIPAL_CLASS = AVThumbnailer

-include GNUmakefile.preamble

include $(GNUSTEP_MAKEFILES)/bundle.make

-include GNUmakefile.postamble

