
PACKAGE_NAME = gworkspace
include $(GNUSTEP_MAKEFILES)/common.make
GNUSTEP_INSTALLATION_DOMAIN = SYSTEM

SUBPROJECTS = \
    FModuleName \
    FModuleKind \
    FModuleSize \
    FModuleOwner \
    FModuleCrDate \
    FModuleModDate \
    FModuleContents \
    FModuleAnnotations


-include GNUmakefile.preamble

-include GNUmakefile.local

include $(GNUSTEP_MAKEFILES)/aggregate.make

include GNUmakefile.postamble


