include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = isowrite-helper

isowrite-helper_OBJC_FILES = main.m

isowrite-helper_INSTALL_DIR = $(GNUSTEP_SYSTEM_TOOLS)

include $(GNUSTEP_MAKEFILES)/tool.make
