include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = formatdisk-helper

formatdisk-helper_OBJC_FILES = main.m

formatdisk-helper_INSTALL_DIR = $(GNUSTEP_SYSTEM_TOOLS)

include $(GNUSTEP_MAKEFILES)/tool.make
