/* t_GSMetaDataInterop.m — macOS <-> Gershwin metadata interoperability.
 *
 * Verifies that GSFileMetadata/GSAppleDouble read REAL metadata produced by
 * a real Mac.  The fixtures (fixtures/ + MANIFEST.plist) are generated by
 * Tools/mac-metadata-interop/generate-fixtures.sh, which needs ssh access to
 * a Mac; this test is hermetic and never touches the network - it only
 * consumes the staged artifacts.  Without staged fixtures it skips cleanly
 * so the suite stays green on machines without a Mac.
 *
 * Covered metadata axes (ground truth captured from macOS itself):
 *   - FinderInfo: type/creator codes, Finder flags, colour label,
 *     invisible + custom-icon bits   (classic 32-byte entry 9)
 *   - Resource fork                (entry 2, byte-exact via hex in manifest)
 *   - Finder tags _kMDItemUserTags (Apple "ATTR" xattr blob inside entry 9)
 *   - Finder comment kMDItemFinderComment (same ATTR blob)
 *   - Spotlight/MDItem view        (mdls ground truth recorded in manifest;
 *                                   asserted where Spotlight reports it)
 *
 * SPDX-License-Identifier: GPL-2.0-or-later OR BSD-2-Clause
 */

#import <Foundation/Foundation.h>
#import "Testing.h"
#include <unistd.h>
#include <stdio.h>

/* The unit under test and its Foundation-only dependencies are compiled
 * in-process (headless), mirroring Tests/GWMetadata/t_GSFileMetadata.m. */
#include "GWMetaXattr.h"
#include "GSAppleDouble.h"
#include "GSFileMetadata.h"
#include "GWMetaArchive.h"
#include "GWMetaXattr.m"
#include "GSAppleDouble.m"
#include "GSFileMetadata.m"
#include "GWMetaArchive.m"

/* ------------------------------------------------------------------ */
/* Locate the staged fixture directory without any build-system help. */
static NSString *
interopFixturesDir(void)
{
  NSMutableArray *candidates = [NSMutableArray array];

  const char *env = getenv("GW_INTEROP_FIXTURES");
  if (env && env[0])
    [candidates addObject: [NSString stringWithUTF8String: env]];

  /* Test tools run as ./obj/<tool> from their own source directory. */
  NSString *exe = [[[NSProcessInfo processInfo] arguments] firstObject];
  if (exe)
    {
      NSString *dir = [exe stringByDeletingLastPathComponent];
      [candidates addObject:
        [[dir stringByDeletingLastPathComponent]
          stringByAppendingPathComponent: @"fixtures"]];
    }

  char *cwdBuf = getcwd(NULL, 0);
  if (cwdBuf)
    {
      NSString *base = [NSString stringWithUTF8String: cwdBuf];
      free(cwdBuf);
      [candidates addObject: [base stringByAppendingPathComponent:
                                        @"fixtures"]];
      [candidates addObject: [base stringByAppendingPathComponent:
        @"Tests/GWMetadata/interop/fixtures"]];
    }

  for (NSString *dir in candidates)
    {
      if ([[NSFileManager defaultManager] fileExistsAtPath:
            [dir stringByAppendingPathComponent: @"MANIFEST.plist"]])
        return dir;
    }
  return nil;
}

static NSString *
fourCC(uint32_t v)
{
  return [NSString stringWithFormat: @"%c%c%c%c",
    (int)((v >> 24) & 0xFF), (int)((v >> 16) & 0xFF),
    (int)((v >> 8) & 0xFF), (int)(v & 0xFF)];
}

/* PASS() formats are printf-style, so object values must be stringified. */
#define U8(obj) ([(obj) UTF8String])

static NSData *
dataFromHex(NSString *hexStr)
{
  NSUInteger len = [hexStr length];
  if (len == 0 || (len % 2) != 0)
    return nil;
  NSMutableData *d = [NSMutableData dataWithCapacity: len / 2];
  const char *bytes = [hexStr UTF8String];
  for (NSUInteger i = 0; i + 1 < len; i += 2)
    {
      unsigned int b;
      if (sscanf(bytes + i, "%2x", &b) != 1)
        return nil;
      uint8_t byte = (uint8_t)b;
      [d appendBytes: &byte length: 1];
    }
  return d;
}


/* Verify one manifest record against the metadata Gershwin reads from
 * `path`.  Used for the staged ._ sidecars AND for files pulled out of
 * the Mac-made zip via GWMetaArchive. */
static void
verifyRecord(NSDictionary *rec, NSString *name, NSString *path)
{
  NSFileManager *fm = [NSFileManager defaultManager];
  BOOL hasMeta = [rec[@"hasMetadata"] boolValue];
  GSFileMetadata *md = [GSFileMetadata metadataForFileAtPath: path
                                                forceSidecar: NO];

  if (!hasMeta)
    {
      BOOL clean = (md == nil)
        || ([md finderInfo] == nil
            && ([md resourceFork] == nil
                || [[md resourceFork] length] == 0)
            && [[md userTags] count] == 0
            && [md finderComment] == nil
            && [md quarantine] == nil);
      PASS(clean, "%s: control file exposes no metadata", U8(name));
      return;
    }
  PASS(md != nil, "%s: metadata parsed from the macOS ._ sidecar",
       U8(name));
  if (md == nil)
    {
      return;
    }

  /* --- FinderInfo-derived properties ---------------------------- */
  NSNumber *tc = rec[@"typeCode"];
  if (tc != nil)
    {
      PASS([md typeCode] == [tc unsignedIntValue],
           "%s: type code is %s (%#x)", U8(name),
           U8(fourCC([tc unsignedIntValue])),
           [tc unsignedIntValue]);
    }
  else
    {
      PASS([md typeCode] == 0, "%s: no type code, reads as 0", U8(name));
    }

  NSNumber *cc = rec[@"creatorCode"];
  if (cc != nil)
    {
      PASS([md creatorCode] == [cc unsignedIntValue],
           "%s: creator code is %s (%#x)", U8(name),
           U8(fourCC([cc unsignedIntValue])),
           [cc unsignedIntValue]);
    }
  else
    {
      PASS([md creatorCode] == 0, "%s: no creator code, reads as 0",
           U8(name));
    }

  NSNumber *ff = rec[@"finderFlags"];
  if (ff != nil)
    {
      PASS([md finderFlags] == [ff unsignedShortValue],
           "%s: Finder flags %#x round-trip", U8(name),
           [ff unsignedShortValue]);
    }

  NSNumber *ln = rec[@"labelNumber"];
  if (ln != nil)
    {
      PASS([md labelNumber] == [ln integerValue],
           "%s: colour label %ld matches fdFlags bits", U8(name),
           (long)[ln integerValue]);
    }

  NSNumber *inv = rec[@"invisible"];
  if (inv != nil)
    {
      PASS([md isInvisible] == [inv boolValue],
           "%s: invisible flag %s", U8(name),
           [inv boolValue] ? "set" : "clear");
    }

  NSNumber *ciFlag = rec[@"customIcon"];
  if (ciFlag != nil)
    {
      PASS([md hasCustomIcon] == [ciFlag boolValue],
           "%s: custom-icon flag %s", U8(name),
           [ciFlag boolValue] ? "set" : "clear");
    }

  /* --- resource fork --------------------------------------------- */
  NSString *rfHex = rec[@"resourceForkHex"];
  if (rfHex != nil)
    {
      NSData *expected = dataFromHex(rfHex);
      PASS(expected != nil && [[md resourceFork] isEqual: expected],
           "%s: resource fork byte-exact (%lu bytes)", U8(name),
           (unsigned long)[expected length]);
    }
  else
    {
      PASS([md resourceFork] == nil || [[md resourceFork] length] == 0,
           "%s: no resource fork reported", U8(name));
    }

  /* --- Finder tags (_kMDItemUserTags, ATTR-blob path) ------------- */
  NSArray *tags = rec[@"userTags"];
  if (tags != nil)
    {
      PASS([[md userTags] isEqual: tags],
           "%s: user tags %s survive the macOS binary plist", U8(name),
           U8([tags description]));
    }

  /* --- Finder comment --------------------------------------------- */
  NSString *comment = rec[@"finderComment"];
  if (comment != nil)
    {
      PASS([comment isEqualToString: [md finderComment]],
           "%s: finder comment '%s' round-trips", U8(name), U8(comment));
    }

  /* --- quarantine --------------------------------------------------
   * copyfile stores the record verbatim in AppleDouble, so pre-ingest
   * bytes must match exactly. */
  NSString *quar = rec[@"quarantine"];
  if (quar != nil)
    {
      PASS([quar isEqualToString: [md quarantine]],
           "%s: quarantine record '%s' round-trips", U8(name), U8(quar));
    }
  else
    {
      PASS([md quarantine] == nil, "%s: no stray quarantine record",
           U8(name));
    }

  /* --- Spotlight / MDItem axis ------------------------------------
   * The manifest records what mdls reports for the same file.  Where
   * Spotlight exposes the comment we must agree with it.  (On macOS
   * 10.6 an externally-set kMDItemFinderComment never reaches the
   * index, so this fires only when the Mac really published one.) */
  NSDictionary *mdls = rec[@"mdls"];
  if ([mdls isKindOfClass: [NSDictionary class]])
    {
      NSString *spotComment = mdls[@"kMDItemComment"];
      if (spotComment != nil)
        {
          PASS([spotComment isEqualToString: [md finderComment]],
               "%s: our comment matches Spotlight's kMDItemComment",
               U8(name));
        }
    }
  (void)fm;
}

int
main(void)
{
  NSAutoreleasePool *arp = [NSAutoreleasePool new];

  NSString *dir = interopFixturesDir();
  if (dir == nil)
    {
      PASS(1, "no fixtures staged - run Tools/mac-metadata-interop/"
              "generate-fixtures.sh with MAC_HOST/MAC_USER/MAC_PASS set; "
              "skipping macOS interop checks");
      [arp release];
      return 0;
    }

  NSData *manifestData = [NSData dataWithContentsOfFile:
    [dir stringByAppendingPathComponent: @"MANIFEST.plist"]];
  PASS(manifestData != nil, "MANIFEST.plist is readable");
  NSDictionary *manifest = [NSPropertyListSerialization
    propertyListWithData: manifestData
                 options: NSPropertyListImmutable
                  format: NULL
                   error: NULL];
  PASS([manifest isKindOfClass: [NSDictionary class]] && [manifest count] > 0,
       "manifest parses to a non-empty dictionary");

  for (NSString *name in [[manifest allKeys]
                            sortedArrayUsingSelector:
                              @selector(compare:)])
    {
      NSDictionary *rec = [manifest objectForKey: name];
      if (![rec isKindOfClass: [NSDictionary class]])
        {
          continue;
        }
      verifyRecord(rec, name,
                   [dir stringByAppendingPathComponent: name]);
    }

  /* --- zip-level forward interop ---------------------------------------
   * The Mac-produced ditto zip (fixtures/macos-made.zip) carries the
   * metadata as __MACOSX AppleDouble companions.  Extract it with
   * GWMetaArchive and hold every record against the same manifest. */
  {
    NSString *zipPath = [dir stringByAppendingPathComponent:
                                   @"macos-made.zip"];
    if ([[NSFileManager defaultManager] fileExistsAtPath: zipPath])
      {
        NSString *dest = [NSTemporaryDirectory()
          stringByAppendingPathComponent:
            [NSString stringWithFormat: @"gw_zip_interop_%d", (int)getpid()]];
        [[NSFileManager defaultManager] removeFileAtPath: dest
                                                 handler: nil];
        NSError *err = nil;
        PASS([GWMetaArchive extractArchive: zipPath
                                     toDir: dest
                                     error: &err],
             "Mac-made zip extracts via GWMetaArchive (%s)",
             err ? [[err description] UTF8String] : "no error");
        for (NSString *name in [[manifest allKeys]
                                  sortedArrayUsingSelector:
                                    @selector(compare:)])
          {
            NSDictionary *rec = [manifest objectForKey: name];
            if ([rec isKindOfClass: [NSDictionary class]])
              {
                verifyRecord(rec, name,
                             [dest stringByAppendingPathComponent: name]);
              }
          }
      }
    else
      {
        PASS(1, "no macos-made.zip staged - skipping zip-level check");
      }
  }

  /* --- structural regression against real Mac bytes -------------------
   * Entry 9 of a macOS sidecar carrying xattrs is 32-byte FinderInfo +
   * padding + Apple's ATTR blob; assert both shapes off the real bytes. */
  {
    NSString *p = [dir stringByAppendingPathComponent:
                    @"file05_combined.txt"];
    NSData *blob = [NSData dataWithContentsOfFile:
      [[p stringByDeletingLastPathComponent]
        stringByAppendingPathComponent: @"._file05_combined.txt"]];
    if (blob != nil)
      {
        GSAppleDouble *ad = [[GSAppleDouble alloc] initWithData: blob];
        PASS(ad != nil, "combined fixture parses as AppleDouble V2");
        PASS([[ad finderInfo] length] == 32,
             "ATTR-bearing entry 9 still exposes exactly 32 FinderInfo bytes");
        NSDictionary *xa = [ad extendedAttributes];
        PASS([xa isKindOfClass: [NSDictionary class]]
             && xa[@"com.apple.metadata:_kMDItemUserTags"] != nil
             && xa[@"com.apple.metadata:kMDItemFinderComment"] != nil,
             "ATTR blob yields tags and comment xattrs");
        DESTROY(ad);
      }
    else
      {
        PASS(1, "no ._file05 sidecar staged - skipping ATTR shape check");
      }
  }

  /* --- emitted-ATTR structural check (no Mac needed) ------------------
   * GSAppleDouble must emit the exact macOS layout so dot_clean/ditto on
   * a real Mac ingest our sidecars: entry 9 first and >32 bytes when
   * xattrs are staged, ATTR header at offset 34 within the entry,
   * data_start right behind the records, total_size = end of entry 9,
   * empty-but-present entry 2 last. */
  {
    GSFileMetadata *md = [[[GSFileMetadata alloc] init] autorelease];
    [md setTypeCode: 'TEXT'];
    [md setCreatorCode: 'ttxt'];
    [md setLabelNumber: 1];
    [md setUserTags: @[ @"Green", @"Release" ]];
    [md setFinderComment: @"roundtrip"];
    NSData *blob = [md appleDoubleData];

    PASS([blob length] > 120, "ATTR-mode blob has plausible size");
    const uint8_t *b = [blob bytes];
    uint16_t count = (uint16_t)((b[24] << 8) | b[25]);
    PASS(count == 2, "ATTR-mode file declares exactly entries 9 and 2");

    uint32_t id1 = ((uint32_t)b[26] << 24) | ((uint32_t)b[27] << 16)
                 | ((uint32_t)b[28] << 8) | b[29];
    uint32_t off1 = ((uint32_t)b[30] << 24) | ((uint32_t)b[31] << 16)
                  | ((uint32_t)b[32] << 8) | b[33];
    uint32_t len1 = ((uint32_t)b[34] << 24) | ((uint32_t)b[35] << 16)
                  | ((uint32_t)b[36] << 8) | b[37];
    uint32_t id2 = ((uint32_t)b[38] << 24) | ((uint32_t)b[39] << 16)
                 | ((uint32_t)b[40] << 8) | b[41];
    uint32_t off2 = ((uint32_t)b[42] << 24) | ((uint32_t)b[43] << 16)
                  | ((uint32_t)b[44] << 8) | b[45];
    PASS(id1 == GSAppleDoubleFinderInfo && id2 == GSAppleDoubleResourceFork,
         "FinderInfo entry comes first, ResourceFork second");
    PASS(off1 == APPLEDOUBLE_HEADER_SIZE + 2 * APPLEDOUBLE_ENTRY_SIZE
         && off2 == [blob length],
         "entry offsets match Mac ordering (FI first, RF last)");

    /* ATTR header inside entry 9. */
    uint32_t attrBase = off1 + 34;
    uint32_t magic = ((uint32_t)b[attrBase] << 24)
                   | ((uint32_t)b[attrBase+1] << 16)
                   | ((uint32_t)b[attrBase+2] << 8) | b[attrBase+3];
    PASS(magic == 0x41545452, "ATTR magic sits at FinderInfo+34");
    uint32_t dstart = ((uint32_t)b[attrBase+12] << 24)
                    | ((uint32_t)b[attrBase+13] << 16)
                    | ((uint32_t)b[attrBase+14] << 8) | b[attrBase+15];
    uint32_t dlen = ((uint32_t)b[attrBase+16] << 24)
                  | ((uint32_t)b[attrBase+17] << 16)
                  | ((uint32_t)b[attrBase+18] << 8) | b[attrBase+19];
    uint16_t numAttrs = (uint16_t)((b[attrBase+34] << 8) | b[attrBase+35]);
    PASS(numAttrs == 2, "ATTR header counts two staged xattrs");
    PASS(dstart == off1 + len1 - dlen,
         "data_start follows the record table exactly");
    PASS(dstart + dlen == off1 + len1,
         "total region ends where entry 9 ends");

    /* And it must parse back identically. */
    GSAppleDouble *back = [[GSAppleDouble alloc] initWithData: blob];
    NSDictionary *xa = [back extendedAttributes];
    NSArray *tagsBack = [NSPropertyListSerialization
      propertyListWithData: xa[@"com.apple.metadata:_kMDItemUserTags"]
                    options: NSPropertyListImmutable
                     format: NULL
                      error: NULL];
    NSArray *wantTags = @[ @"Green", @"Release" ];
    PASS([tagsBack isEqual: wantTags],
         "emitted ATTR blob round-trips tags through our own parser");
    NSString *commentBack = [NSPropertyListSerialization
      propertyListWithData: xa[@"com.apple.metadata:kMDItemFinderComment"]
                    options: NSPropertyListImmutable
                     format: NULL
                      error: NULL];
    PASS([commentBack isEqualToString: @"roundtrip"],
         "emitted ATTR blob round-trips the comment (binary plist)");
    DESTROY(commentBack);
    DESTROY(back);
  }

  /* --- classic emission stays classic ---------------------------------- */
  {
    GSFileMetadata *md = [[[GSFileMetadata alloc] init] autorelease];
    [md setTypeCode: 'TEXT'];
    NSData *blob = [md appleDoubleData];
    const uint8_t *b = [blob bytes];
    uint16_t count = (uint16_t)((b[24] << 8) | b[25]);
    uint32_t len1 = ((uint32_t)b[34] << 24) | ((uint32_t)b[35] << 16)
                  | ((uint32_t)b[36] << 8) | b[37];
    PASS(count == 2 && len1 == 32,
         "xattr-free metadata emits the classic 32-byte FinderInfo entry");
  }

  [GSFileMetadata invalidateAllCachedMetadata];
  [arp release];
  return 0;
}
