#!/usr/bin/env python3
"""Add real translations for all missing keys in languages I know.
Usage: python3 translate-missing.py <lang> <strings_file>
  lang: fr, it, es, pt, nl, de
"""
import re, sys, os

# All source keys to translate (from _() macro — standard menu items)
# and NSLocalizedString keys (technical/UI strings)

FR = {
    # Go menu
    "Go": "Aller",
    "Back": "Retour",
    "Forward": "Avant",
    "Enclosing Folder": "Dossier parent",
    "Recents": "Récents",
    "Home": "Dossier personnel",
    "Computer": "Ordinateur",
    "Transfer": "Transfert",
    "Utilities": "Utilitaires",
    "Go to Folder...": "Aller au dossier...",
    "Connect to Server...": "Connexion au serveur...",
    "Connect to Server:": "Connexion au serveur :",
    "Go to Folder:": "Aller au dossier :",
    # View menu
    "Enter Full Screen": "Plein écran",
    "as Icons": "en icônes",
    "as List": "en liste",
    "as Columns": "en colonnes",
    "as Gallery": "en galerie",
    "Use Stacks": "Utiliser les piles",
    "Sort By": "Trier par",
    "Show Preview": "Afficher l'aperçu",
    "Show Preview Options": "Options d'aperçu",
    "Show View Options": "Options d'affichage",
    "Show Toolbar": "Afficher la barre d'outils",
    "Hide Toolbar": "Masquer la barre d'outils",
    "Show Sidebar": "Afficher le panneau latéral",
    "Hide Sidebar": "Masquer le panneau latéral",
    "Customize Toolbar...": "Personnaliser la barre d'outils...",
    "Browsing": "Navigation",
    "Spatial": "Spatial",
    "Set Browsing as Default": "Navigation par défaut",
    "Set Spatial as Default": "Spatial par défaut",
    "View Behavior": "Comportement d'affichage",
    # Window menu
    "Window": "Fenêtre",
    "Minimize": "Réduire",
    "Zoom": "Zoom",
    "Cycle Through Windows": "Parcourir les fenêtres",
    # File menu / Context menu
    "New Workspace Window": "Nouvelle fenêtre Workspace",
    "Make Alias": "Créer un alias",
    "Move to Trash": "Déplacer vers la corbeille",
    "Share": "Partager",
    "Find": "Rechercher",
    "Print": "Imprimer",
    # Edit menu
    "Undo": "Annuler",
    "Redo": "Rétablir",
    # Workspace (app) menu
    "About This Computer": "À propos de cet ordinateur",
    "About Workspace": "À propos de Workspace",
    "Hide Workspace": "Masquer Workspace",
    "Workspace Help": "Aide Workspace",
    "Gershwin Help": "Aide Gershwin",
    "New to Gershwin? Get Started": "Vous découvrez Gershwin ? Premiers pas",
    "Keyboard Shortcuts": "Raccourcis clavier",
    "Feedback": "Commentaires",
    "Legal & Regulatory": "Mentions légales",
    "Show Clipboard": "Afficher le presse-papiers",
    "Start Dictation": "Dicter",
    "Symbols": "Symboles",
    "Tags": "Étiquettes",
    # Help menu
    "Help": "Aide",
    "Quick Look": "Aperçu rapide",
    # Dock / Desktop
    "Bottom": "Bas",
    "Bring to Front": "Mettre au premier plan",
    "Bring All to Front": "Tout mettre au premier plan",
    "Keep in Dock": "Garder dans le Dock",
    "Remove from Dock": "Retirer du Dock",
    "Show In File Viewer": "Afficher dans le visionneur",
    "Unhide": "Afficher",
    # Network
    "AFP Server": "Serveur AFP",
    "SFTP Server": "Serveur SFTP",
    "WebDAV Server": "Serveur WebDAV",
    "WebDAV Server (Secure)": "Serveur WebDAV (sécurisé)",
    "WebDAV Connection Failed": "Échec de connexion WebDAV",
    "Connect to SFTP Server": "Connexion au serveur SFTP",
    "Connect to WebDAV Server": "Connexion au serveur WebDAV",
    "Enter credentials for %@:": "Entrez les identifiants pour %@ :",
    "Connection Failed": "Échec de connexion",
    "Connect": "Connecter",
    "Network Location": "Emplacement réseau",
    "Network Server": "Serveur réseau",
    "Network User": "Utilisateur réseau",
    "Local User": "Utilisateur local",
    "Local": "Local",
    "Network": "Réseau",
    "Could not connect to %@\n\nCheck the hostname and try again.": "Impossible de se connecter à %@\n\nVérifiez le nom d'hôte et réessayez.",
    "Could not connect to %@.\n\nError: %@": "Impossible de se connecter à %@.\n\nErreur : %@",
    "Failed to mount SFTP volume:\n\n%@": "Échec du montage du volume SFTP :\n\n%@",
    "Failed to unmount %@.": "Échec du démontage de %@.",
    "Failed to unmount %@: %@": "Échec du démontage de %@ : %@",
    "Mount Failed": "Échec du montage",
    "Unmount failed.": "Échec du démontage.",
    "Unmounting partitions...": "Démontage des partitions...",
    "Invalid mount point.": "Point de montage invalide.",
    "Cannot Mount": "Impossible de monter",
    "Cannot determine device for the selected mount point.": "Impossible de déterminer le périphérique pour le point de montage sélectionné.",
    "Cannot determine device information for the selected mount point.": "Impossible de déterminer les informations du périphérique pour le point de montage sélectionné.",
    "Cannot read information for the selected device.": "Impossible de lire les informations du périphérique sélectionné.",
    "Target is not a physical device mount point.": "La cible n'est pas un point de montage de périphérique physique.",
    "System Disk": "Disque système",
    "System": "Système",
    "Volume Removed Unexpectedly": "Volume retiré inopinément",
    "The following volumes were removed without being properly ejected:\n\n%@\n\n": "Les volumes suivants ont été retirés sans être éjectés correctement :\n\n%@\n\n",
    "The volume at the following path was removed without being properly ejected:\n\n%@\n\n": "Le volume au chemin suivant a été retiré sans être éjecté correctement :\n\n%@\n\n",
    "You are not allowed to umount\n": "Vous n'êtes pas autorisé à démonter\n",
    "You cannot eject the root filesystem": "Vous ne pouvez pas éjecter le système de fichiers racine",
    "Volumes": "Volumes",
    "Domains": "Domaines",
    "available": "disponible",
    # AVFS / SSHFS
    "AVFS Error": "Erreur AVFS",
    "AVFS Not Installed": "AVFS non installé",
    "SSHFS Not Installed": "SSHFS non installé",
    "sshpass Not Installed": "sshpass non installé",
    "AF volume mounting is not yet implemented.": "Le montage de volumes AFP n'est pas encore implémenté.",
    "AVFS (A Virtual File System) is required to browse archive contents but is not installed on your system.\n\nTo install it:\n• On Debian/Ubuntu: sudo apt-get install avfs\n• On Fedora/RHEL: sudo dnf install avfs\n• On Arch: sudo pacman -S avfs\n• From source: https://avf.sourceforge.net/": "AVFS (A Virtual File System) est requis pour parcourir le contenu des archives mais n'est pas installé sur votre système.\n\nPour l'installer :\n• Sur Debian/Ubuntu : sudo apt-get install avfs\n• Sur Fedora/RHEL : sudo dnf install avfs\n• Sur Arch : sudo pacman -S avfs\n• Depuis les sources : https://avf.sourceforge.net/",
    "FUSE sshfs is required to mount SFTP network volumes but is not installed on your system.\n\nTo install it:\n• On Debian/Ubuntu: sudo apt-get install sshfs\n• On Fedora/RHEL: sudo dnf install fuse-sshfs\n• On Arch: sudo pacman -S sshfs": "FUSE sshfs est requis pour monter les volumes réseau SFTP mais n'est pas installé sur votre système.\n\nPour l'installer :\n• Sur Debian/Ubuntu : sudo apt-get install sshfs\n• Sur Fedora/RHEL : sudo dnf install fuse-sshfs\n• Sur Arch : sudo pacman -S sshfs",
    "sshpass is required for password-based SFTP authentication but is not installed on your system.\n\nTo install it:\n• On Debian/Ubuntu: sudo apt-get install sshpass\n• On Fedora/RHEL: sudo dnf install sshpass\n• On Arch: sudo pacman -S sshpass\n\nAlternatively, you can set up SSH key authentication to connect without a password.": "sshpass est requis pour l'authentification SFTP par mot de passe mais n'est pas installé sur votre système.\n\nPour l'installer :\n• Sur Debian/Ubuntu : sudo apt-get install sshpass\n• Sur Fedora/RHEL : sudo dnf install sshpass\n• Sur Arch : sudo pacman -S sshpass\n\nVous pouvez aussi configurer une authentification par clé SSH pour vous connecter sans mot de passe.",
    "Failed to start the AVFS daemon. Please check that AVFS is properly installed.": "Impossible de démarrer le démon AVFS. Vérifiez que AVFS est correctement installé.",
    "The network service does not have a valid hostname.": "Le service réseau n'a pas de nom d'hôte valide.",
    # ISO write
    "An ISO write operation is already in progress for this device.": "Une opération d'écriture ISO est déjà en cours pour ce périphérique.",
    "Are you sure you want to cancel?\n\nThe target device may be left in an inconsistent state and will need to be reformatted.": "Êtes-vous sûr de vouloir annuler ?\n\nLe périphérique cible pourrait être laissé dans un état incohérent et devra être reformaté.",
    "Cancel Write": "Annuler l'écriture",
    "Cancel Write?": "Annuler l'écriture ?",
    "Continue Writing": "Continuer l'écriture",
    "Copy File": "Copier le fichier",
    "Could not find formatdisk-helper. Please reinstall Workspace tools.": "Impossible de trouver formatdisk-helper. Veuillez réinstaller les outils Workspace.",
    "Done.": "Terminé.",
    "Format": "Formater",
    "Format Complete": "Formatage terminé",
    "Format Disk...": "Formater le disque...",
    "Format Failed": "Échec du formatage",
    "Formatting failed.": "Le formatage a échoué.",
    "ISO File Dropped": "Fichier ISO déposé",
    "ISO Write Error": "Erreur d'écriture ISO",
    "Not an ISO or supported disk image file.": "Ce n'est pas un fichier ISO ou une image disque prise en charge.",
    "The disk was formatted as FAT32.": "Le disque a été formaté en FAT32.",
    "The ISO image has been successfully written to the device.\n\nThe new volume should appear on your desktop when you plug the device in.": "L'image ISO a été écrite avec succès sur le périphérique.\n\nLe nouveau volume devrait apparaître sur votre bureau lorsque vous branchez le périphérique.",
    "The write operation was cancelled. The target device may be in an inconsistent state and should be reformatted before use.": "L'opération d'écriture a été annulée. Le périphérique cible pourrait être dans un état incohérent et devrait être reformaté avant utilisation.",
    "Verifying...": "Vérification...",
    "Write Cancelled": "Écriture annulée",
    "Write Complete": "Écriture terminée",
    "Write to Device": "Écrire sur le périphérique",
    "Writing image": "Écriture de l'image",
    "Writing image to device...": "Écriture de l'image sur le périphérique...",
    "Preparing...": "Préparation...",
    "Cancelling...": "Annulation...",
    "Failed.": "Échec.",
    "(failed to launch)": "(échec du lancement)",
    # Logout / Restart / Shutdown
    "Are you sure you want to quit\nall applications and restart now?": "Êtes-vous sûr de vouloir quitter\ntoutes les applications et redémarrer maintenant ?",
    "Are you sure you want to quit\nall applications and shut down now?": "Êtes-vous sûr de vouloir quitter\ntoutes les applications et éteindre maintenant ?",
    "Failed to execute shutdown command.": "Échec de l'exécution de la commande d'extinction.",
    "Kill applications": "Forcer la fermeture des applications",
    "Restart": "Redémarrer",
    "Restart...": "Redémarrer...",
    "Shut Down": "Éteindre",
    "Shut Down...": "Éteindre...",
    "The following applications:": "Les applications suivantes :",
    "refuse to terminate.": "refusent de se terminer.",
    # Sidebar items
    "Applications": "Applications",
    "Documents": "Documents",
    "Downloads": "Téléchargements",
    "Music": "Musique",
    "Pictures": "Images",
    "Videos": "Vidéos",
    "Date Modified": "Date de modification",
    "Parent": "Parent",
    "Kind": "Type",
    # Archive operations
    "Compressing...": "Compression...",
    "Extracting...": "Extraction...",
    "Extract": "Extraire",
    "Compress": "Compresser",
    # Context menu
    "Clean Up": "Nettoyer",
    "Clean Up By": "Nettoyer par",
    "Get Info": "Lire les informations",
    "Label": "Étiquette",
    "Eject": "Éjecter",
    # Labels
    "None": "Aucun",
    "Grey": "Gris",
    "Green": "Vert",
    "Purple": "Violet",
    "Blue": "Bleu",
    "Yellow": "Jaune",
    "Red": "Rouge",
    "Orange": "Orange",
    # Finder / Search
    "Searching in:": "Recherche dans :",
    "No search criteria!": "Aucun critère de recherche !",
    "New Live Search": "Nouvelle recherche live",
    "New Viewer": "Nouveau visionneur",
    "can't create the Live Search folder": "Impossible de créer le dossier de recherche live",
    "the search tool connection died!": "la connexion à l'outil de recherche a été interrompue !",
    "No Finder modules! Quitting now.": "Aucun module Finder. Fermeture.",
    "Modules:": "Modules :",
    "unable to launch the search task.": "impossible de lancer la tâche de recherche.",
    "unable to launch the updater task.": "impossible de lancer la tâche de mise à jour.",
    "Update now": "Mettre à jour maintenant",
    "updater connection died!": "connexion du service de mise à jour interrompue !",
    "fswatcher notifications disabled!": "notifications fswatcher désactivées !",
    "The fswatcher connection died.\nDo you want to restart it?": "La connexion fswatcher a été interrompue.\nVoulez-vous la redémarrer ?",
    "The mdextractor connection died.\nDo you want to restart it?": "La connexion mdextractor a été interrompue.\nVoulez-vous la redémarrer ?",
    "ddbd connection died.": "connexion ddbd interrompue.",
    # Generic operations
    "Operation Failed": "Opération échouée",
    "Operation In Progress": "Opération en cours",
    "Wait the operations to terminate!": "Attendez la fin des opérations !",
    "Workspace is logging out!": "Workspace se déconnecte !",
    "No executable found!": "Aucun exécutable trouvé !",
    "is not a valid application!": "n'est pas une application valide !",
    "seems not a valid application!": "ne semble pas être une application valide !",
    "No name supplied!": "Aucun nom fourni !",
    "Can't create the Desktop directory!": "Impossible de créer le dossier Bureau !",
    "The Desktop directory has been deleted! Quitting now!": "Le dossier Bureau a été supprimé ! Fermeture.",
    "Can't edit a directory!": "Impossible de modifier un dossier !",
    ": no such file or directory!": ": fichier ou dossier introuvable !",
    "open": "ouvrir",
    "Open in Terminal": "Ouvrir dans le Terminal",
    "Terminal.app": "Terminal.app",
    # Time intervals
    "one minute": "une minute",
    "one hour": "une heure",
    "10 minutes": "10 minutes",
    "30 minutes": "30 minutes",
    "2 hours": "2 heures",
    "3 hours": "3 heures",
    "5 minutes": "5 minutes",
    "6 hours": "6 heures",
    "12 hours": "12 heures",
    "a day": "un jour",
    # File attributes
    "kind": "type",
    "total": "total",
    "unknown": "inconnu",
    "unknown volume size": "taille du volume inconnue",
    "(unlabeled)": "(sans étiquette)",
    # Recycler
    "You can't open a document that is in the Recycler!": "Vous ne pouvez pas ouvrir un document qui se trouve dans la Corbeille !",
    "You can't do this in the Recycler!": "Vous ne pouvez pas faire cela dans la Corbeille !",
    "You can't create a new folder in the Recycler!": "Vous ne pouvez pas créer un nouveau dossier dans la Corbeille !",
    "You can't create a new file in the Recycler!": "Vous ne pouvez pas créer un nouveau fichier dans la Corbeille !",
    "You can't duplicate files in the Recycler!": "Vous ne pouvez pas dupliquer des fichiers dans la Corbeille !",
    "You can't move objects with multiple parent paths!": "Vous ne pouvez pas déplacer des objets avec plusieurs chemins parents !",
    "Empty Trash": "Vider la corbeille",
    # Recycler (extra for full coverage)
    "the Recycler": "la Corbeille",
    "\nto the Recycler": "\nvers la Corbeille",
    "Move from the Recycler ": "Déplacer de la Corbeille ",
    "Recycle: ": "Corbeille : ",
    "Recycler: ": "Corbeille : ",
    "Recycler": "Corbeille",
    "In": "Dans",
    "Empty the Recycler?": "Vider la Corbeille ?",
    "Some items have the same name;\ndo you want to substitute them?": "Certains éléments ont le même nom ;\nvoulez-vous les remplacer ?",
    # Other
    "Other": "Autre",
    "No Contents Inspectors found!": "Aucun inspecteur de contenu trouvé !",
    "Classic": "Classique",
    "Modern": "Moderne",
    "scale": "adapté",
    "Position:": "Position :",
    # Status window durations
    "%d:%02d remaining": "%d:%02d restant",
    "%d:%02d:%02d remaining": "%d:%02d:%02d restant",
    # Miscellaneous
    "elements": "éléments",
    "recursive": "récursif",
    "Choose Image": "Choisir une image",
    "Username:": "Nom d'utilisateur :",
    "Password:": "Mot de passe :",
    "Label Color...": "Couleur d'étiquette...",
    "Not Implemented": "Non implémenté",
    "no autoupdate": "pas de mise à jour automatique",
    "starting:": "démarrage :",
    "You cannot format the root filesystem.": "Vous ne pouvez pas formater le système de fichiers racine.",
    "You do not have write permission\nfor": "Vous n'avez pas la permission d'écriture\npour",
    "Select and move the files to hide or to show": "Sélectionnez et déplacez les fichiers à masquer ou à afficher",
    "Show status window": "Afficher la fenêtre d'état",
    "Uncheck the buttons to allow automatic confirmation": "Décochez les boutons pour permettre la confirmation automatique",
    "of file operations": "des opérations sur les fichiers",
    "Check this option to show a status window": "Cochez cette option pour afficher une fenêtre d'état",
    "during the file operations": "pendant les opérations sur les fichiers",
    "Number of saved paths": "Nombre de chemins sauvegardés",
    "Single Click Launch": "Lancer par un clic",
    "You can get help by pressing the Option key (the mouse cursor becomes a question mark) and then clicking on any user interface element.": "Vous pouvez obtenir de l'aide en appuyant sur la touche Option (le curseur de la souris devient un point d'interrogation) puis en cliquant sur n'importe quel élément de l'interface.",
    "Already at the root directory": "Déjà dans le répertoire racine",
    "Cannot access %@": "Impossible d'accéder à %@",
    "Could not create or access the %@ folder": "Impossible de créer ou d'accéder au dossier %@",
    "Could not open URL:\n\n%@": "Impossible d'ouvrir l'URL :\n\n%@",
    "Invalid URL format": "Format d'URL invalide",
    "URL must include a hostname": "L'URL doit inclure un nom d'hôte",
    "URL must include a scheme (sftp://, webdav://, webdavs://)": "L'URL doit inclure un schéma (sftp://, webdav://, webdavs://)",
    "Supported URL schemes: sftp://, webdav://, webdavs://": "Schémas d'URL pris en charge : sftp://, webdav://, webdavs://",
    "More Info...": "Plus d'informations...",
    # System info
    "About %@": "À propos de %@",
    "OS": "Système d'exploitation",
    "Kernel": "Noyau",
    "Model": "Modèle",
    "Memory": "Mémoire",
    "Processor": "Processeur",
    "Date Created": "Date de création",
    # Low disk space
    "Low Disk Space": "Espace disque faible",
    "The startup disk has less than 3%% free space.\n\n": "Le disque de démarrage a moins de 3%% d'espace libre.\n\n",
    "The startup disk has less than 3%% free space.\n\nOnly %.1f%% (%llu MB) available.": "Le disque de démarrage a moins de 3%% d'espace libre.\n\nSeulement %.1f%% (%llu Mo) disponible.",
    # X11
    "X11 Server": "Serveur X11",
    # Alerts
    "The Utilities folder could not be found at:\n\n%@": "Le dossier Utilitaires n'a pas pu être trouvé à :\n\n%@",
    # Full-length keys
    "Erases all data on %@ and reformats as FAT32.\n\nDevice: %@%@%@\n\nPartitions:\n%@\nThis cannot be undone.": "Efface toutes les données sur %@ et reformate en FAT32.\n\nPériphérique : %@%@%@\n\nPartitions :\n%@\nCette opération est irréversible.",
    "The following volumes were removed without being properly ejected:\n\n%@\n\nAlways eject removable volumes before unplugging them to prevent data loss and avoid crashes.": "Les volumes suivants ont été retirés sans être éjectés correctement :\n\n%@\n\nÉjectez toujours les volumes amovibles avant de les débrancher pour éviter la perte de données et les plantages.",
    "The volume at the following path was removed without being properly ejected:\n\n%@\n\nAlways eject removable volumes before unplugging them to prevent data loss and avoid crashes.": "Le volume au chemin suivant a été retiré sans être éjecté correctement :\n\n%@\n\nÉjectez toujours les volumes amovibles avant de les débrancher pour éviter la perte de données et les plantages.",
}

IT = {
    "Go": "Vai",
    "Back": "Indietro",
    "Forward": "Avanti",
    "Enclosing Folder": "Cartella superiore",
    "Recents": "Recenti",
    "Home": "Home",
    "Computer": "Computer",
    "Transfer": "Trasferimento",
    "Utilities": "Utility",
    "Go to Folder...": "Vai alla cartella...",
    "Connect to Server...": "Connetti al server...",
    "Connect to Server:": "Connetti al server :",
    "Go to Folder:": "Vai alla cartella :",
    "Enter Full Screen": "Schermo intero",
    "as Icons": "come icone",
    "as List": "come elenco",
    "as Columns": "come colonne",
    "as Gallery": "come galleria",
    "Use Stacks": "Usa pile",
    "Sort By": "Ordina per",
    "Show Preview": "Mostra anteprima",
    "Show Preview Options": "Opzioni anteprima",
    "Show View Options": "Opzioni di visualizzazione",
    "Show Toolbar": "Mostra barra strumenti",
    "Hide Toolbar": "Nascondi barra strumenti",
    "Show Sidebar": "Mostra barra laterale",
    "Hide Sidebar": "Nascondi barra laterale",
    "Customize Toolbar...": "Personalizza barra strumenti...",
    "Browsing": "Navigazione",
    "Spatial": "Spaziale",
    "Set Browsing as Default": "Imposta navigazione come predefinita",
    "Set Spatial as Default": "Imposta spaziale come predefinito",
    "View Behavior": "Comportamento vista",
    "Window": "Finestra",
    "Minimize": "Riduci a icona",
    "Zoom": "Ingrandisci",
    "Cycle Through Windows": "Scorri le finestre",
    "New Workspace Window": "Nuova finestra Workspace",
    "Make Alias": "Crea alias",
    "Move to Trash": "Sposta nel Cestino",
    "Share": "Condividi",
    "Find": "Trova",
    "Print": "Stampa",
    "Undo": "Annulla",
    "Redo": "Ripeti",
    "About This Computer": "Informazioni su questo computer",
    "About Workspace": "Informazioni su Workspace",
    "Hide Workspace": "Nascondi Workspace",
    "Workspace Help": "Aiuto Workspace",
    "Gershwin Help": "Aiuto Gershwin",
    "New to Gershwin? Get Started": "Novità di Gershwin? Inizia",
    "Keyboard Shortcuts": "Scorciatoie da tastiera",
    "Feedback": "Feedback",
    "Legal & Regulatory": "Note legali",
    "Show Clipboard": "Mostra appunti",
    "Start Dictation": "Dettatura",
    "Symbols": "Simboli",
    "Tags": "Tag",
    "Help": "Aiuto",
    "Quick Look": "Anteprima rapida",
    "Bottom": "In basso",
    "Bring to Front": "Porta in primo piano",
    "Bring All to Front": "Porta tutto in primo piano",
    "Keep in Dock": "Mantieni nel Dock",
    "Remove from Dock": "Rimuovi dal Dock",
    "Show In File Viewer": "Mostra nel visualizzatore",
    "Unhide": "Mostra",
    "AFP Server": "Server AFP",
    "SFTP Server": "Server SFTP",
    "WebDAV Server": "Server WebDAV",
    "WebDAV Server (Secure)": "Server WebDAV (sicuro)",
    "WebDAV Connection Failed": "Connessione WebDAV fallita",
    "Connect to SFTP Server": "Connetti al server SFTP",
    "Connect to WebDAV Server": "Connetti al server WebDAV",
    "Enter credentials for %@:": "Inserisci credenziali per %@ :",
    "Connection Failed": "Connessione fallita",
    "Connect": "Connetti",
    "Network Location": "Posizione di rete",
    "Network Server": "Server di rete",
    "Network User": "Utente di rete",
    "Local User": "Utente locale",
    "Local": "Locale",
    "Network": "Rete",
    "Could not connect to %@\n\nCheck the hostname and try again.": "Impossibile connettersi a %@\n\nControlla il nome host e riprova.",
    "Could not connect to %@.\n\nError: %@": "Impossibile connettersi a %@.\n\nErrore : %@",
    "Failed to mount SFTP volume:\n\n%@": "Montaggio volume SFTP fallito :\n\n%@",
    "Failed to unmount %@.": "Smontaggio di %@ fallito.",
    "Failed to unmount %@: %@": "Smontaggio di %@ fallito : %@",
    "Mount Failed": "Montaggio fallito",
    "Unmount failed.": "Smontaggio fallito.",
    "Unmounting partitions...": "Smontaggio partizioni...",
    "Invalid mount point.": "Punto di mount non valido.",
    "Cannot Mount": "Impossibile montare",
    "Cannot determine device for the selected mount point.": "Impossibile determinare il dispositivo per il punto di mount selezionato.",
    "Cannot determine device information for the selected mount point.": "Impossibile determinare le informazioni del dispositivo per il punto di mount selezionato.",
    "Cannot read information for the selected device.": "Impossibile leggere le informazioni del dispositivo selezionato.",
    "Target is not a physical device mount point.": "Il target non è un punto di mount di un dispositivo fisico.",
    "System Disk": "Disco di sistema",
    "System": "Sistema",
    "Volume Removed Unexpectedly": "Volume rimosso inaspettatamente",
    "You are not allowed to umount\n": "Non sei autorizzato a smontare\n",
    "You cannot eject the root filesystem": "Non puoi espellere il filesystem di root",
    "Volumes": "Volumi",
    "Domains": "Domini",
    "available": "disponibile",
    "AVFS Error": "Errore AVFS",
    "AVFS Not Installed": "AVFS non installato",
    "SSHFS Not Installed": "SSHFS non installato",
    "sshpass Not Installed": "sshpass non installato",
    "An ISO write operation is already in progress for this device.": "Un'operazione di scrittura ISO è già in corso per questo dispositivo.",
    "Are you sure you want to cancel?\n\nThe target device may be left in an inconsistent state and will need to be reformatted.": "Sei sicuro di voler annullare?\n\nIl dispositivo di destinazione potrebbe rimanere in uno stato incoerente e dovrà essere riformattato.",
    "Cancel Write": "Annulla scrittura",
    "Cancel Write?": "Annullare la scrittura?",
    "Continue Writing": "Continua scrittura",
    "Copy File": "Copia file",
    "Could not find formatdisk-helper. Please reinstall Workspace tools.": "Impossibile trovare formatdisk-helper. Reinstalla gli strumenti Workspace.",
    "Done.": "Completato.",
    "Format": "Formatta",
    "Format Complete": "Formattazione completata",
    "Format Disk...": "Formatta disco...",
    "Format Failed": "Formattazione fallita",
    "Formatting failed.": "Formattazione fallita.",
    "ISO File Dropped": "File ISO rilasciato",
    "ISO Write Error": "Errore scrittura ISO",
    "Not an ISO or supported disk image file.": "Non è un file ISO o un'immagine disco supportata.",
    "The disk was formatted as FAT32.": "Il disco è stato formattato come FAT32.",
    "The ISO image has been successfully written to the device.\n\nThe new volume should appear on your desktop when you plug the device in.": "L'immagine ISO è stata scritta con successo sul dispositivo.\n\nIl nuovo volume dovrebbe apparire sulla scrivania quando colleghi il dispositivo.",
    "The write operation was cancelled. The target device may be in an inconsistent state and should be reformatted before use.": "L'operazione di scrittura è stata annullata. Il dispositivo di destinazione potrebbe essere in uno stato incoerente e dovrebbe essere riformattato prima dell'uso.",
    "Verifying...": "Verifica...",
    "Write Cancelled": "Scrittura annullata",
    "Write Complete": "Scrittura completata",
    "Write to Device": "Scrivi sul dispositivo",
    "Writing image": "Scrittura immagine",
    "Writing image to device...": "Scrittura immagine sul dispositivo...",
    "Preparing...": "Preparazione...",
    "Cancelling...": "Annullamento...",
    "Failed.": "Fallito.",
    "(failed to launch)": "(lancio fallito)",
    "Are you sure you want to quit\nall applications and restart now?": "Sei sicuro di voler uscire\nda tutte le applicazioni e riavviare ora?",
    "Are you sure you want to quit\nall applications and shut down now?": "Sei sicuro di voler uscire\nda tutte le applicazioni e spegnere ora?",
    "Failed to execute shutdown command.": "Esecuzione del comando di spegnimento fallita.",
    "Kill applications": "Termina applicazioni",
    "Restart": "Riavvia",
    "Restart...": "Riavvia...",
    "Shut Down": "Spegni",
    "Shut Down...": "Spegni...",
    "The following applications:": "Le seguenti applicazioni :",
    "refuse to terminate.": "rifiutano di terminare.",
    "Applications": "Applicazioni",
    "Documents": "Documenti",
    "Downloads": "Download",
    "Music": "Musica",
    "Pictures": "Immagini",
    "Videos": "Video",
    "Date Modified": "Data modifica",
    "Parent": "Padre",
    "Kind": "Tipo",
    "Compressing...": "Compressione...",
    "Extracting...": "Estrazione...",
    "Extract": "Estrai",
    "Compress": "Comprimi",
    "Clean Up": "Pulisci",
    "Clean Up By": "Pulisci per",
    "Get Info": "Informazioni",
    "Label": "Etichetta",
    "Eject": "Espelli",
    "None": "Nessuno",
    "Grey": "Grigio",
    "Green": "Verde",
    "Purple": "Viola",
    "Blue": "Blu",
    "Yellow": "Giallo",
    "Red": "Rosso",
    "Orange": "Arancione",
    "Searching in:": "Cerca in :",
    "No search criteria!": "Nessun criterio di ricerca!",
    "New Live Search": "Nuova ricerca live",
    "New Viewer": "Nuovo visualizzatore",
    "can't create the Live Search folder": "impossibile creare la cartella di ricerca live",
    "the search tool connection died!": "connessione allo strumento di ricerca interrotta!",
    "No Finder modules! Quitting now.": "Nessun modulo Finder. Chiusura.",
    "Modules:": "Moduli :",
    "unable to launch the search task.": "impossibile avviare l'attività di ricerca.",
    "unable to launch the updater task.": "impossibile avviare l'attività di aggiornamento.",
    "Update now": "Aggiorna ora",
    "updater connection died!": "connessione aggiornamento interrotta!",
    "fswatcher notifications disabled!": "notifiche fswatcher disabilitate!",
    "The fswatcher connection died.\nDo you want to restart it?": "La connessione fswatcher è stata interrotta.\nVuoi riavviarla?",
    "The mdextractor connection died.\nDo you want to restart it?": "La connessione mdextractor è stata interrotta.\nVuoi riavviarla?",
    "ddbd connection died.": "connessione ddbd interrotta.",
    "Operation Failed": "Operazione fallita",
    "Operation In Progress": "Operazione in corso",
    "Wait the operations to terminate!": "Attendi la fine delle operazioni!",
    "Workspace is logging out!": "Workspace sta uscendo!",
    "No executable found!": "Nessun eseguibile trovato!",
    "is not a valid application!": "non è un'applicazione valida!",
    "seems not a valid application!": "non sembra un'applicazione valida!",
    "No name supplied!": "Nessun nome fornito!",
    "Can't create the Desktop directory!": "Impossibile creare la cartella Scrivania!",
    "The Desktop directory has been deleted! Quitting now!": "La cartella Scrivania è stata eliminata! Chiusura.",
    "Can't edit a directory!": "Impossibile modificare una cartella!",
    ": no such file or directory!": ": file o directory inesistente!",
    "open": "apri",
    "Open in Terminal": "Apri nel Terminale",
    "one minute": "un minuto",
    "one hour": "un'ora",
    "10 minutes": "10 minuti",
    "30 minutes": "30 minuti",
    "2 hours": "2 ore",
    "3 hours": "3 ore",
    "5 minutes": "5 minuti",
    "6 hours": "6 ore",
    "12 hours": "12 ore",
    "a day": "un giorno",
    "kind": "tipo",
    "total": "totale",
    "unknown": "sconosciuto",
    "unknown volume size": "dimensione volume sconosciuta",
    "(unlabeled)": "(senza etichetta)",
    "You can't open a document that is in the Recycler!": "Non puoi aprire un documento che si trova nel Cestino!",
    "You can't do this in the Recycler!": "Non puoi farlo nel Cestino!",
    "You can't create a new folder in the Recycler!": "Non puoi creare una nuova cartella nel Cestino!",
    "You can't create a new file in the Recycler!": "Non puoi creare un nuovo file nel Cestino!",
    "You can't duplicate files in the Recycler!": "Non puoi duplicare file nel Cestino!",
    "You can't move objects with multiple parent paths!": "Non puoi spostare oggetti con percorsi padre multipli!",
    "Empty Trash": "Svuota cestino",
    "the Recycler": "il Cestino",
    "\nto the Recycler": "\nnel Cestino",
    "Move from the Recycler ": "Sposta dal Cestino ",
    "Recycle: ": "Cestino : ",
    "Recycler: ": "Cestino : ",
    "Recycler": "Cestino",
    "In": "In",
    "Empty the Recycler?": "Svuotare il Cestino?",
    "Some items have the same name;\ndo you want to substitute them?": "Alcuni elementi hanno lo stesso nome;\nvuoi sostituirli?",
    "Other": "Altro",
    "No Contents Inspectors found!": "Nessun ispettore contenuti trovato!",
    "Classic": "Classico",
    "Modern": "Moderno",
    "scale": "adatta",
    "Position:": "Posizione :",
    "%d:%02d remaining": "%d:%02d rimanenti",
    "%d:%02d:%02d remaining": "%d:%02d:%02d rimanenti",
    "elements": "elementi",
    "recursive": "ricorsivo",
    "Choose Image": "Scegli immagine",
    "Username:": "Nome utente :",
    "Password:": "Password :",
    "Label Color...": "Colore etichetta...",
    "Not Implemented": "Non implementato",
    "no autoupdate": "nessun aggiornamento automatico",
    "starting:": "avvio :",
    "You cannot format the root filesystem.": "Non puoi formattare il filesystem di root.",
    "You do not have write permission\nfor": "Non hai il permesso di scrittura\nper",
    "Single Click Launch": "Avvio con un clic",
    "Already at the root directory": "Già nella directory root",
    "Cannot access %@": "Impossibile accedere a %@",
    "Could not create or access the %@ folder": "Impossibile creare o accedere alla cartella %@",
    "Could not open URL:\n\n%@": "Impossibile aprire URL :\n\n%@",
    "Invalid URL format": "Formato URL non valido",
    "URL must include a hostname": "L'URL deve includere un nome host",
    "URL must include a scheme (sftp://, webdav://, webdavs://)": "L'URL deve includere uno schema (sftp://, webdav://, webdavs://)",
    "Supported URL schemes: sftp://, webdav://, webdavs://": "Schemi URL supportati : sftp://, webdav://, webdavs://",
    "More Info...": "Più informazioni...",
    "About %@": "Informazioni su %@",
    "OS": "Sistema operativo",
    "Kernel": "Kernel",
    "Model": "Modello",
    "Memory": "Memoria",
    "Processor": "Processore",
    "Date Created": "Data creazione",
    "Low Disk Space": "Poco spazio su disco",
    "X11 Server": "Server X11",
    "The Utilities folder could not be found at:\n\n%@": "La cartella Utility non è stata trovata in :\n\n%@",
}

# Spanish translations (all missing keys)
ES = {
    "Go": "Ir",
    "Back": "Atrás",
    "Forward": "Adelante",
    "Enclosing Folder": "Carpeta contenedora",
    "Recents": "Recientes",
    "Home": "Inicio",
    "Computer": "Equipo",
    "Transfer": "Transferencia",
    "Utilities": "Utilidades",
    "Go to Folder...": "Ir a la carpeta...",
    "Connect to Server...": "Conectar al servidor...",
    "Connect to Server:": "Conectar al servidor :",
    "Go to Folder:": "Ir a la carpeta :",
    "Enter Full Screen": "Pantalla completa",
    "as Icons": "como iconos",
    "as List": "como lista",
    "as Columns": "como columnas",
    "as Gallery": "como galería",
    "Use Stacks": "Usar pilas",
    "Sort By": "Ordenar por",
    "Show Preview": "Mostrar vista previa",
    "Show Preview Options": "Opciones de vista previa",
    "Show View Options": "Opciones de vista",
    "Show Toolbar": "Mostrar barra de herramientas",
    "Hide Toolbar": "Ocultar barra de herramientas",
    "Show Sidebar": "Mostrar barra lateral",
    "Hide Sidebar": "Ocultar barra lateral",
    "Customize Toolbar...": "Personalizar barra de herramientas...",
    "Browsing": "Navegación",
    "Spatial": "Espacial",
    "Set Browsing as Default": "Establecer navegación como predeterminada",
    "Set Spatial as Default": "Establecer espacial como predeterminado",
    "View Behavior": "Comportamiento de vista",
    "Window": "Ventana",
    "Minimize": "Minimizar",
    "Zoom": "Zoom",
    "Cycle Through Windows": "Recorrer ventanas",
    "New Workspace Window": "Nueva ventana de Workspace",
    "Make Alias": "Crear alias",
    "Move to Trash": "Mover a la papelera",
    "Share": "Compartir",
    "Find": "Buscar",
    "Print": "Imprimir",
    "Undo": "Deshacer",
    "Redo": "Rehacer",
    "About This Computer": "Acerca de este equipo",
    "About Workspace": "Acerca de Workspace",
    "Hide Workspace": "Ocultar Workspace",
    "Workspace Help": "Ayuda de Workspace",
    "Gershwin Help": "Ayuda de Gershwin",
    "New to Gershwin? Get Started": "¿Nuevo en Gershwin? Comience",
    "Keyboard Shortcuts": "Atajos de teclado",
    "Feedback": "Comentarios",
    "Legal & Regulatory": "Aviso legal",
    "Show Clipboard": "Mostrar portapapeles",
    "Start Dictation": "Iniciar dictado",
    "Symbols": "Símbolos",
    "Tags": "Etiquetas",
    "Help": "Ayuda",
    "Quick Look": "Vista rápida",
    "Bottom": "Abajo",
    "Bring to Front": "Traer al frente",
    "Bring All to Front": "Traer todo al frente",
    "Keep in Dock": "Mantener en el Dock",
    "Remove from Dock": "Eliminar del Dock",
    "Show In File Viewer": "Mostrar en el visor",
    "Unhide": "Mostrar",
    "AFP Server": "Servidor AFP",
    "SFTP Server": "Servidor SFTP",
    "WebDAV Server": "Servidor WebDAV",
    "WebDAV Server (Secure)": "Servidor WebDAV (seguro)",
    "WebDAV Connection Failed": "Conexión WebDAV fallida",
    "Connect to SFTP Server": "Conectar al servidor SFTP",
    "Connect to WebDAV Server": "Conectar al servidor WebDAV",
    "Enter credentials for %@:": "Introduzca credenciales para %@ :",
    "Connection Failed": "Conexión fallida",
    "Connect": "Conectar",
    "Network Location": "Ubicación de red",
    "Network Server": "Servidor de red",
    "Network User": "Usuario de red",
    "Local User": "Usuario local",
    "Local": "Local",
    "Network": "Red",
    "Could not connect to %@\n\nCheck the hostname and try again.": "No se pudo conectar a %@\n\nVerifique el nombre de host e intente de nuevo.",
    "Could not connect to %@.\n\nError: %@": "No se pudo conectar a %@.\n\nError : %@",
    "Failed to mount SFTP volume:\n\n%@": "Error al montar el volumen SFTP :\n\n%@",
    "Failed to unmount %@.": "Error al desmontar %@.",
    "Failed to unmount %@: %@": "Error al desmontar %@ : %@",
    "Mount Failed": "Montaje fallido",
    "Unmount failed.": "Desmontaje fallido.",
    "Unmounting partitions...": "Desmontando particiones...",
    "Invalid mount point.": "Punto de montaje no válido.",
    "Cannot Mount": "No se puede montar",
    "System Disk": "Disco del sistema",
    "System": "Sistema",
    "Volume Removed Unexpectedly": "Volumen retirado inesperadamente",
    "You are not allowed to umount\n": "No tiene permiso para desmontar\n",
    "You cannot eject the root filesystem": "No puede expulsar el sistema de archivos raíz",
    "Volumes": "Volúmenes",
    "Domains": "Dominios",
    "available": "disponible",
    "AVFS Error": "Error de AVFS",
    "AVFS Not Installed": "AVFS no instalado",
    "SSHFS Not Installed": "SSHFS no instalado",
    "sshpass Not Installed": "sshpass no instalado",
    "An ISO write operation is already in progress for this device.": "Ya hay una operación de escritura ISO en curso para este dispositivo.",
    "Cancel Write": "Cancelar escritura",
    "Cancel Write?": "¿Cancelar escritura?",
    "Continue Writing": "Continuar escritura",
    "Copy File": "Copiar archivo",
    "Could not find formatdisk-helper. Please reinstall Workspace tools.": "No se pudo encontrar formatdisk-helper. Reinstale las herramientas de Workspace.",
    "Done.": "Completado.",
    "Format": "Formatear",
    "Format Complete": "Formateo completado",
    "Format Disk...": "Formatear disco...",
    "Format Failed": "Formateo fallido",
    "Formatting failed.": "El formateo falló.",
    "ISO File Dropped": "Archivo ISO soltado",
    "ISO Write Error": "Error de escritura ISO",
    "Not an ISO or supported disk image file.": "No es un archivo ISO o imagen de disco compatible.",
    "The disk was formatted as FAT32.": "El disco fue formateado como FAT32.",
    "The ISO image has been successfully written to the device.\n\nThe new volume should appear on your desktop when you plug the device in.": "La imagen ISO se ha escrito correctamente en el dispositivo.\n\nEl nuevo volumen debería aparecer en su escritorio cuando conecte el dispositivo.",
    "Verifying...": "Verificando...",
    "Write Cancelled": "Escritura cancelada",
    "Write Complete": "Escritura completada",
    "Write to Device": "Escribir en el dispositivo",
    "Writing image": "Escribiendo imagen",
    "Writing image to device...": "Escribiendo imagen en el dispositivo...",
    "Preparing...": "Preparando...",
    "Cancelling...": "Cancelando...",
    "Failed.": "Falló.",
    "(failed to launch)": "(fallo al lanzar)",
    "Restart": "Reiniciar",
    "Restart...": "Reiniciar...",
    "Shut Down": "Apagar",
    "Shut Down...": "Apagar...",
    "Applications": "Aplicaciones",
    "Documents": "Documentos",
    "Downloads": "Descargas",
    "Music": "Música",
    "Pictures": "Imágenes",
    "Videos": "Vídeos",
    "Date Modified": "Fecha de modificación",
    "Parent": "Padre",
    "Kind": "Tipo",
    "Compressing...": "Comprimiendo...",
    "Extracting...": "Extrayendo...",
    "Extract": "Extraer",
    "Compress": "Comprimir",
    "Clean Up": "Limpiar",
    "Clean Up By": "Limpiar por",
    "Get Info": "Obtener información",
    "Label": "Etiqueta",
    "Eject": "Expulsar",
    "None": "Ninguno",
    "Grey": "Gris",
    "Green": "Verde",
    "Purple": "Púrpura",
    "Blue": "Azul",
    "Yellow": "Amarillo",
    "Red": "Rojo",
    "Orange": "Naranja",
    "Searching in:": "Buscando en :",
    "New Live Search": "Nueva búsqueda en vivo",
    "New Viewer": "Nuevo visor",
    "can't create the Live Search folder": "no se puede crear la carpeta de búsqueda en vivo",
    "the search tool connection died!": "conexión con la herramienta de búsqueda interrumpida",
    "No Finder modules! Quitting now.": "No hay módulos de Finder. Cerrando.",
    "Modules:": "Módulos :",
    "unable to launch the search task.": "no se puede lanzar la tarea de búsqueda.",
    "unable to launch the updater task.": "no se puede lanzar la tarea de actualización.",
    "Update now": "Actualizar ahora",
    "updater connection died!": "conexión de actualización interrumpida",
    "fswatcher notifications disabled!": "notificaciones de fswatcher desactivadas",
    "ddbd connection died.": "conexión ddbd interrumpida",
    "Operation Failed": "Operación fallida",
    "Operation In Progress": "Operación en curso",
    "Wait the operations to terminate!": "¡Espere a que terminen las operaciones!",
    "Workspace is logging out!": "¡Workspace está cerrando sesión!",
    "No executable found!": "¡No se encontró ningún ejecutable!",
    "is not a valid application!": "¡no es una aplicación válida!",
    "seems not a valid application!": "¡no parece una aplicación válida!",
    "No name supplied!": "¡No se proporcionó ningún nombre!",
    "Can't create the Desktop directory!": "¡No se puede crear el directorio Escritorio!",
    "The Desktop directory has been deleted! Quitting now!": "¡El directorio Escritorio ha sido eliminado! Cerrando.",
    "Can't edit a directory!": "¡No se puede editar un directorio!",
    ": no such file or directory!": ": archivo o directorio inexistente",
    "open": "abrir",
    "Open in Terminal": "Abrir en Terminal",
    "one minute": "un minuto",
    "one hour": "una hora",
    "10 minutes": "10 minutos",
    "30 minutes": "30 minutos",
    "2 hours": "2 horas",
    "3 hours": "3 horas",
    "5 minutes": "5 minutos",
    "6 hours": "6 horas",
    "12 hours": "12 horas",
    "a day": "un día",
    "kind": "tipo",
    "total": "total",
    "unknown": "desconocido",
    "unknown volume size": "tamaño de volumen desconocido",
    "(unlabeled)": "(sin etiqueta)",
    "You can't open a document that is in the Recycler!": "¡No se puede abrir un documento que está en la Papelera!",
    "You can't do this in the Recycler!": "¡No se puede hacer esto en la Papelera!",
    "You can't create a new folder in the Recycler!": "¡No se puede crear una nueva carpeta en la Papelera!",
    "You can't create a new file in the Recycler!": "¡No se puede crear un nuevo archivo en la Papelera!",
    "You can't duplicate files in the Recycler!": "¡No se pueden duplicar archivos en la Papelera!",
    "You can't move objects with multiple parent paths!": "¡No se pueden mover objetos con rutas padre múltiples!",
    "Empty Trash": "Vaciar papelera",
    "the Recycler": "la Papelera",
    "\nto the Recycler": "\na la Papelera",
    "Move from the Recycler ": "Mover desde la Papelera ",
    "Recycle: ": "Papelera : ",
    "Recycler: ": "Papelera : ",
    "Recycler": "Papelera",
    "In": "En",
    "Empty the Recycler?": "¿Vaciar la Papelera?",
    "Other": "Otro",
    "Classic": "Clásico",
    "Modern": "Moderno",
    "scale": "escalado",
    "Position:": "Posición :",
    "%d:%02d remaining": "%d:%02d restante",
    "%d:%02d:%02d remaining": "%d:%02d:%02d restante",
    "elements": "elementos",
    "recursive": "recursivo",
    "Choose Image": "Elegir imagen",
    "Username:": "Nombre de usuario :",
    "Password:": "Contraseña :",
    "Label Color...": "Color de etiqueta...",
    "Not Implemented": "No implementado",
    "no autoupdate": "sin actualización automática",
    "starting:": "iniciando :",
    "You cannot format the root filesystem.": "No se puede formatear el sistema de archivos raíz.",
    "You do not have write permission\nfor": "No tiene permisos de escritura\npara",
    "Single Click Launch": "Inicio con un clic",
    "Already at the root directory": "Ya está en el directorio raíz",
    "Cannot access %@": "No se puede acceder a %@",
    "Could not create or access the %@ folder": "No se pudo crear o acceder a la carpeta %@",
    "Could not open URL:\n\n%@": "No se pudo abrir la URL :\n\n%@",
    "Invalid URL format": "Formato de URL no válido",
    "URL must include a hostname": "La URL debe incluir un nombre de host",
    "About %@": "Acerca de %@",
    "OS": "Sistema operativo",
    "Kernel": "Kernel",
    "Model": "Modelo",
    "Memory": "Memoria",
    "Processor": "Procesador",
    "Date Created": "Fecha de creación",
    "Low Disk Space": "Poco espacio en disco",
    "X11 Server": "Servidor X11",
}

def escape_strings(s):
    """Escape a Python string for .strings format."""
    # Order matters: do backslash first to avoid double-escaping
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    s = s.replace('\r', '\\r')
    s = s.replace('\t', '\\t')
    # Smart quotes -> unicode escapes
    s = s.replace('\u201c', '\\u201c')
    s = s.replace('\u201d', '\\u201d')
    s = s.replace('\u201e', '\\u201e')
    s = s.replace('\u2018', '\\u2018')
    s = s.replace('\u2019', '\\u2019')
    s = s.replace('\u2022', '\\u2022')
    return s

def unescape_strings(s):
    """Reverse: .strings format -> Python string."""
    s = s.replace('\\n', '\n')
    s = s.replace('\\r', '\r')
    s = s.replace('\\t', '\t')
    s = s.replace('\\"', '"')
    s = s.replace('\\\\', '\\')
    s = s.replace('\\u201c', '\u201c')
    s = s.replace('\\u201d', '\u201d')
    s = s.replace('\\u201e', '\u201e')
    s = s.replace('\\u2018', '\u2018')
    s = s.replace('\\u2019', '\u2019')
    s = s.replace('\\u00fc', '\u00fc')
    s = s.replace('\\u00f6', '\u00f6')
    s = s.replace('\\u00e4', '\u00e4')
    s = s.replace('\\u00df', '\u00df')
    s = s.replace('\\u2022', '\u2022')
    return s

def add_translations(path, trans_dict):
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()

    # Build set of existing keys (as they appear in the file)
    normalized = re.sub(r'(")\s*\n\s*=\s*', r'\1 = ', text)
    pat = re.compile(r'^"((?:[^"\\]|\\.)*)"\s*=\s*"(?:[^"\\]|\\.)*"\s*;\s*$', re.MULTILINE)
    existing_file_keys = {m.group(1) for m in pat.finditer(normalized)}

    added = 0
    for key, val in sorted(trans_dict.items(), key=lambda x: len(x[0]), reverse=True):
        # Check if key already exists in file (in file-native escape format)
        escaped_key = escape_strings(key)
        if escaped_key in existing_file_keys:
            continue
        # Also check with alternative smart quote styles
        alt1 = escaped_key.replace('\\u201c', '\u201c').replace('\\u201d', '\u201d')
        if alt1 in existing_file_keys:
            continue
        alt2 = escaped_key.replace('\u201c', '\\u201c').replace('\u201d', '\\u201d')
        if alt2 in existing_file_keys:
            continue

        escaped_val = escape_strings(val)
        text += '\n"{}" = "{}";\n'.format(escaped_key, escaped_val)
        added += 1

    if added > 0:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(text)
    return added

PT = {
    "Go": "Ir",
    "View": "Ver",
    "Show": "Mostrar",
    "Edit": "Editar",
    "Back": "Voltar",
    "Forward": "Avançar",
    "Enclosing Folder": "Pasta superior",
    "Recents": "Recentes",
    "Home": "Início",
    "Computer": "Computador",
    "Transfer": "Transferência",
    "Utilities": "Utilitários",
    "Go to Folder...": "Ir para pasta...",
    "Connect to Server...": "Ligar ao servidor...",
    "Enter Full Screen": "Ecrã inteiro",
    "as Icons": "como ícones",
    "as List": "como lista",
    "as Columns": "como colunas",
    "as Gallery": "como galeria",
    "Sort By": "Ordenar por",
    "Show Preview": "Mostrar pré-visualização",
    "Show View Options": "Opções de visualização",
    "Show Toolbar": "Mostrar barra de ferramentas",
    "Hide Toolbar": "Ocultar barra de ferramentas",
    "Show Sidebar": "Mostrar barra lateral",
    "Hide Sidebar": "Ocultar barra lateral",
    "Customize Toolbar...": "Personalizar barra de ferramentas...",
    "Window": "Janela",
    "Minimize": "Minimizar",
    "Zoom": "Ampliar",
    "Cycle Through Windows": "Percorrer janelas",
    "New Workspace Window": "Nova janela do Workspace",
    "Make Alias": "Criar alias",
    "Move to Trash": "Mover para o lixo",
    "Share": "Partilhar",
    "Find": "Procurar",
    "Print": "Imprimir",
    "Undo": "Anular",
    "Redo": "Refazer",
    "About This Computer": "Sobre este computador",
    "About Workspace": "Sobre o Workspace",
    "Hide Workspace": "Ocultar o Workspace",
    "Workspace Help": "Ajuda do Workspace",
    "New to Gershwin? Get Started": "Novo no Gershwin? Comece",
    "Keyboard Shortcuts": "Atalhos de teclado",
    "Feedback": "Comentários",
    "Legal & Regulatory": "Avisos legais",
    "Show Clipboard": "Mostrar área de transferência",
    "Start Dictation": "Iniciar ditado",
    "Symbols": "Símbolos",
    "Tags": "Etiquetas",
    "Help": "Ajuda",
    "Quick Look": "Visualização rápida",
    "Bottom": "Fundo",
    "Bring to Front": "Trazer para a frente",
    "Bring All to Front": "Trazer tudo para a frente",
    "Keep in Dock": "Manter no Dock",
    "Remove from Dock": "Remover do Dock",
    "Show In File Viewer": "Mostrar no visualizador",
    "Unhide": "Mostrar",
    "AFP Server": "Servidor AFP",
    "SFTP Server": "Servidor SFTP",
    "WebDAV Server": "Servidor WebDAV",
    "WebDAV Server (Secure)": "Servidor WebDAV (seguro)",
    "WebDAV Connection Failed": "Falha na ligação WebDAV",
    "Connect to SFTP Server": "Ligar ao servidor SFTP",
    "Connect to WebDAV Server": "Ligar ao servidor WebDAV",
    "Connection Failed": "Falha na ligação",
    "Connect": "Ligar",
    "Network Location": "Localização de rede",
    "Network Server": "Servidor de rede",
    "Network User": "Utilizador de rede",
    "Local User": "Utilizador local",
    "Local": "Local",
    "Network": "Rede",
    "Mount Failed": "Montagem falhou",
    "Unmount failed.": "Desmontagem falhou.",
    "Volumes": "Volumes",
    "Domains": "Domínios",
    "available": "disponível",
    "AVFS Error": "Erro AVFS",
    "AVFS Not Installed": "AVFS não instalado",
    "SSHFS Not Installed": "SSHFS não instalado",
    "sshpass Not Installed": "sshpass não instalado",
    "Format": "Formatar",
    "Format Complete": "Formatação concluída",
    "Format Disk...": "Formatar disco...",
    "Format Failed": "Formatação falhou",
    "Formatting failed.": "A formatação falhou.",
    "Verifying...": "A verificar...",
    "Write Cancelled": "Escrita cancelada",
    "Write Complete": "Escrita concluída",
    "Write to Device": "Escrever no dispositivo",
    "Preparing...": "A preparar...",
    "Cancelling...": "A cancelar...",
    "Failed.": "Falhou.",
    "Restart": "Reiniciar",
    "Shut Down": "Desligar",
    "Applications": "Aplicações",
    "Documents": "Documentos",
    "Downloads": "Transferências",
    "Music": "Música",
    "Pictures": "Imagens",
    "Videos": "Vídeos",
    "Date Modified": "Data de modificação",
    "Parent": "Pai",
    "Kind": "Tipo",
    "Compress": "Comprimir",
    "Extract": "Extrair",
    "Clean Up": "Limpar",
    "Get Info": "Obter informações",
    "Label": "Etiqueta",
    "Eject": "Ejetar",
    "None": "Nenhum",
    "Grey": "Cinzento",
    "Green": "Verde",
    "Purple": "Roxo",
    "Blue": "Azul",
    "Yellow": "Amarelo",
    "Red": "Vermelho",
    "Orange": "Laranja",
    "Operation Failed": "Operação falhou",
    "Operation In Progress": "Operação em curso",
    "Workspace is logging out!": "O Workspace está a terminar sessão!",
    "open": "abrir",
    "Open in Terminal": "Abrir no Terminal",
    "unknown": "desconhecido",
    "unknown volume size": "tamanho do volume desconhecido",
    "(unlabeled)": "(sem etiqueta)",
    "Empty Trash": "Esvaziar lixo",
    "the Recycler": "o Lixo",
    "Recycler": "Lixo",
    "In": "Em",
    "Other": "Outro",
    "Classic": "Clássico",
    "Modern": "Moderno",
    "scale": "escalado",
    "Position:": "Posição :",
    "elements": "elementos",
    "recursive": "recursivo",
    "Choose Image": "Escolher imagem",
    "Username:": "Nome de utilizador :",
    "Password:": "Palavra-passe :",
    "Not Implemented": "Não implementado",
    "starting:": "a iniciar :",
    "Single Click Launch": "Iniciar com um clique",
    "OS": "Sistema operativo",
    "Kernel": "Kernel",
    "Model": "Modelo",
    "Memory": "Memória",
    "Processor": "Processador",
    "Date Created": "Data de criação",
    "Low Disk Space": "Pouco espaço em disco",
    "X11 Server": "Servidor X11",
    "About %@": "Sobre %@",
}

NL = {
    "Go": "Ga",
    "Back": "Terug",
    "Forward": "Vooruit",
    "Enclosing Folder": "Bovenliggende map",
    "Recents": "Recente items",
    "Home": "Thuis",
    "Computer": "Computer",
    "Transfer": "Overdracht",
    "Utilities": "Hulpprogramma's",
    "Go to Folder...": "Ga naar map...",
    "Connect to Server...": "Verbind met server...",
    "Enter Full Screen": "Volledig scherm",
    "as Icons": "als pictogrammen",
    "as List": "als lijst",
    "as Columns": "als kolommen",
    "as Gallery": "als galerij",
    "Sort By": "Sorteer op",
    "Show Preview": "Toon voorbeeld",
    "Show View Options": "Beeldopties",
    "Show Toolbar": "Toon werkbalk",
    "Hide Toolbar": "Verberg werkbalk",
    "Show Sidebar": "Toon zijbalk",
    "Hide Sidebar": "Verberg zijbalk",
    "Customize Toolbar...": "Werkbalk aanpassen...",
    "Browsing": "Bladeren",
    "Spatial": "Ruimtelijk",
    "Window": "Venster",
    "Minimize": "Minimaliseren",
    "Zoom": "Zoomen",
    "Cycle Through Windows": "Door vensters bladeren",
    "New Workspace Window": "Nieuw Workspace-venster",
    "Make Alias": "Alias maken",
    "Move to Trash": "Naar prullenmand",
    "Share": "Delen",
    "Find": "Zoek",
    "Print": "Print",
    "Undo": "Ongedaan maken",
    "Redo": "Opnieuw",
    "About This Computer": "Over deze computer",
    "About Workspace": "Over Workspace",
    "Hide Workspace": "Verberg Workspace",
    "Workspace Help": "Workspace-help",
    "New to Gershwin? Get Started": "Nieuw bij Gershwin? Begin hier",
    "Keyboard Shortcuts": "Sneltoetsen",
    "Feedback": "Feedback",
    "Legal & Regulatory": "Juridisch",
    "Show Clipboard": "Toon klembord",
    "Start Dictation": "Dictee starten",
    "Symbols": "Symbolen",
    "Tags": "Labels",
    "Help": "Help",
    "Quick Look": "Snelle weergave",
    "Bottom": "Onder",
    "Bring to Front": "Naar voorgrond",
    "Bring All to Front": "Alles naar voorgrond",
    "Keep in Dock": "Bewaar in Dock",
    "Remove from Dock": "Verwijder uit Dock",
    "Show In File Viewer": "Toon in viewer",
    "Unhide": "Tonen",
    "AFP Server": "AFP-server",
    "SFTP Server": "SFTP-server",
    "WebDAV Server": "WebDAV-server",
    "WebDAV Server (Secure)": "WebDAV-server (beveiligd)",
    "WebDAV Connection Failed": "WebDAV-verbinding mislukt",
    "Connect to SFTP Server": "Verbind met SFTP-server",
    "Connect to WebDAV Server": "Verbind met WebDAV-server",
    "Connection Failed": "Verbinding mislukt",
    "Connect": "Verbinden",
    "Network Location": "Netwerklocatie",
    "Network Server": "Netwerkserver",
    "Network User": "Netwerkgebruiker",
    "Local User": "Lokale gebruiker",
    "Local": "Lokaal",
    "Network": "Netwerk",
    "Mount Failed": "Mounten mislukt",
    "Unmount failed.": "Ontkoppelen mislukt.",
    "Volumes": "Volumes",
    "Domains": "Domeinen",
    "available": "beschikbaar",
    "AVFS Error": "AVFS-fout",
    "AVFS Not Installed": "AVFS niet geïnstalleerd",
    "SSHFS Not Installed": "SSHFS niet geïnstalleerd",
    "sshpass Not Installed": "sshpass niet geïnstalleerd",
    "Format": "Formatteren",
    "Format Complete": "Formatteren voltooid",
    "Format Disk...": "Schijf formatteren...",
    "Format Failed": "Formatteren mislukt",
    "Formatting failed.": "Formatteren mislukt.",
    "Verifying...": "Controleren...",
    "Write Cancelled": "Schrijven geannuleerd",
    "Write Complete": "Schrijven voltooid",
    "Write to Device": "Naar apparaat schrijven",
    "Preparing...": "Voorbereiden...",
    "Cancelling...": "Annuleren...",
    "Failed.": "Mislukt.",
    "Restart": "Herstart",
    "Shut Down": "Uitschakelen",
    "Applications": "Toepassingen",
    "Documents": "Documenten",
    "Downloads": "Downloads",
    "Music": "Muziek",
    "Pictures": "Afbeeldingen",
    "Videos": "Video's",
    "Date Modified": "Wijzigingsdatum",
    "Parent": "Bovenliggend",
    "Kind": "Soort",
    "Compress": "Comprimeren",
    "Extract": "Uitpakken",
    "Clean Up": "Opschonen",
    "Get Info": "Info",
    "Label": "Label",
    "Eject": "Uitwerpen",
    "None": "Geen",
    "Grey": "Grijs",
    "Green": "Groen",
    "Purple": "Paars",
    "Blue": "Blauw",
    "Yellow": "Geel",
    "Red": "Rood",
    "Orange": "Oranje",
    "Operation Failed": "Bewerking mislukt",
    "Operation In Progress": "Bewerking bezig",
    "open": "openen",
    "Open in Terminal": "Openen in Terminal",
    "unknown": "onbekend",
    "unknown volume size": "onbekende volumegrootte",
    "(unlabeled)": "(zonder label)",
    "Empty Trash": "Prullenmand legen",
    "the Recycler": "de Prullenmand",
    "Recycler": "Prullenmand",
    "In": "In",
    "Other": "Anders",
    "Classic": "Klassiek",
    "Modern": "Modern",
    "scale": "geschikt",
    "Position:": "Positie :",
    "elements": "elementen",
    "recursive": "recursief",
    "Choose Image": "Kies afbeelding",
    "Username:": "Gebruikersnaam :",
    "Password:": "Wachtwoord :",
    "Not Implemented": "Niet geïmplementeerd",
    "starting:": "starten :",
    "Single Click Launch": "Starten met één klik",
    "OS": "Besturingssysteem",
    "Kernel": "Kernel",
    "Model": "Model",
    "Memory": "Geheugen",
    "Processor": "Processor",
    "Date Created": "Aanmaakdatum",
    "Low Disk Space": "Weinig schijfruimte",
    "X11 Server": "X11-server",
    "About %@": "Over %@",
    "Annotations": "Annotaties",
}

if __name__ == '__main__':
    lang_map = {'fr': ('French', FR), 'it': ('Italian', IT), 'es': ('Spanish', ES),
                'pt': ('Portuguese', PT), 'nl': ('Dutch', NL)}
    for code, (name, trans) in lang_map.items():
        path = f'Workspace/Resources/{name}.lproj/Localizable.strings'
        n = add_translations(path, trans)
        print(f'{name}: added {n} translations')
